# try
try...except...finally...的错误处理机制

如果没有错误发生，可以在except语句块后面加一个else，当没有错误发生时，会自动执行else语句：

```py
>>> try:
...   print("try....")
...   r = 10 / 2
...   print("result: ",r)
... except ZeroDivisionError as e:
...   print("except: ",e)
... else:
...   print("no error!")
... finally:
...   print("finally")
...
try....
result:  5.0
no error!
finally

```

# 调用栈

# 记录错误：import logging
python内置的logging模块可以记录错误信息：

# 抛出错误：raise